### ISSUE TITLE
Kraft v 0.9.2 update

### ISSUE THREAD

**Issue by ordiovince** [chorry/autoKraft#6]
Hi,

The script isn't working with the latest version (v 0.9.0) of Kraft.

**Comment by chorry** [comment]
Thanks for info, i'll check for broken functionality

**Comment by chorry** [comment]
@ordiovince well, it seems to be working well with current (0.9.3) version
Could you specify what exactly is not working for you, as well as your browser version?

**Comment by ordiovince** [comment]
This code posses problems:

```
    updateSettings: function(currentSettings, newSettings) {
        return $.extend(true, newSettings, currentSettings);
    },
```

It says `Uncaught TypeError: $.extend is not a function(…)`

I'm using Google Chrome 50.0.2661.94 m

**Comment by chorry** [comment]
Oh, i think i get it.
$.extend is a call for jQuery `extend` function, so it seems that jQuery library was not loaded for some reason. jQ is required and loaded by the keepCraft itself 
`12:<script type="text/javascript" src="jquery/jquery.min.js"></script>`
Just refresh the page few times, and problem should go away - to make sure, you can type `jQuery` in dev console, output should be something like:

```
< jQuery
> function (e,t){return new b.fn.init(e,t,r)}
```

**Comment by ordiovince** [comment]
Oh, you are absolutely wright, reloading the page a few time did the trick ;)

Thank you very much!
